version: '3.8'

services:
  rat-server:
    image: rat:latest
    container_name: rat_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${ENV_PORT}:${ENV_PORT}"
    environment:
      - ENV_PORT=${ENV_PORT}
      - ENV_HOST=${ENV_HOST}
      - DATABASE_URL=postgres://postgres:password@rat_postgres:5432/ratdb?sslmode=disable
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: rat_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ratdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
